# Generated by Django 4.0.2 on 2022-04-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_userfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='following_user',
        ),
    ]
